apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "Africa/Nairobi"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "720"
  N8N_LOG_LEVEL: "warn"
